version: '3.9'

services:
  prochainweb-database:
    image: postgres:latest
    restart: 'no'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: playgit
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d playgit']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5436:5432
    expose:
      - 5432
    volumes:
      - prochainweb-database:/var/lib/postgresql/data

volumes:
  prochainweb-database:
